{
  users {
    id
    stats(from: "2016-01-01", to: "2017-08-02") {
      comments
      likes
    }
    posts {
      body
      stats(from: "2016-01-01", to: "2017-08-02") {
        comments
        likes
      }
    }
  }
}